spring:
  config:
    activate:
      on-profile: "test"

build:
  version: "1.0"

accounts:
  message: "Cards related to test APIs "
  contactDetails:
    name: "Cards Product Owner"
    email: "john@test.com"
  onCallSupport:
    - (555) 555-5555
    - (444) 444-4444