version: '3.8'
services:
  config-service:
    build: ../configServer
    ports:
      - "8071:8071"
    networks:
      - microservices-network

  accounts-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-service:8071"
      SPRING_CLOUD_CONFIG_URI: "http://config-service:8071"
    networks:
      - microservices-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
