spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C://Users//Youcode//Documents//configs"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


server:
  port: 8071