# Use the official OpenJDK image for Java 17
FROM openjdk:17-slim

# Specify the argument for the jar file
ARG JAR_FILE=target/*.jar

# Copy the built jar file into the Docker image as app.jar
COPY ${JAR_FILE} app.jar

# Expose the port your application uses
EXPOSE 8090

# Command to execute the Spring Boot application
ENTRYPOINT ["java", "-jar", "/app.jar"]
