build:
  version: "1.0"

loans:
  message: "Loans related to prod APIs "
  contactDetails:
    name: "Loans Product Owner"
    email: "John@Prod.com"
  onCallSupport:
    - (555) 555-5555
    - (444) 444-4444