spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_test.yml"
      - "application_prod.yml"
  profiles:
    active: "test"
  h2:
    console:
      enabled: true



accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@doe.com"
  onCallSupport:
    - (555) 555-5555
    - (444) 444-4444

server:
  port: 8080
