build:
  version: "1.0"

loans:
  message: "Loans related to test APIs "
  contactDetails:
    name: "Loans Product Owner"
    email: "john@test.com"
  onCallSupport:
    - (555) 555-5555
    - (444) 444-4444