spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
    elasticsearch:
      client:
        uris: http://localhost:9200

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: SpringMongoDBelasticSearch

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
          elasticsearch: DEBUG
